### ISSUE TITLE
Add CodeSignatureVerification for StatPlus_mac_LE.download

### ISSUE THREAD

**Issue by cwhits** [autopkg/orchard-recipes#1]
StatPlus is code-signed so CodeSignatureVerification can be added. If I find time I can submit a PR for it.

Here's the requirement:
`anchor apple generic and identifier "com.analystsoft.mst.pro2" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "58ZUUA887T")`

**Comment by fuzzylogiq** [comment]
Thanks. We will implement this very shortly. In fact, we're going to go through all of our recipes and figure out which ones need CodeSignatureVerification and add them accordingly.

**Comment by fuzzylogiq** [comment]
Fixed in https://github.com/autopkg/orchard-recipes/commit/03d0ebe4af7a547655cbdcca476572f7b9af8ac8
