### ISSUE TITLE
Mono recipe duplicate

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/orchard-recipes#2]
Hi there

looks like we both have recipes for Mono framework. https://github.com/autopkg/MichalMMac-recipes/tree/master/MonoFramework

Perhaps we could merge then under one repo so there is only single set of Mono recipes in AutoPkg search.

**Comment by AltMeta** [comment]
Hi MichalMMac

That sounds good to me, how would you like to go about this?
If I'd have previously seen a recipe, I wouldn't have written one ! 

I shall write an override for your recipe and check that everything works as expected locally, later this week. Once that has happened I'm happy to remove my recipes, if that is how you would like to proceed?

**Comment by MichalMMac** [comment]
Sure. 

Mine has `CodeSignatureVerifier`. Yours have little more complex regular expression and is's sending User Agent headers.  If you could spare few minutes to compare both XMLs so we can put together one good version :-)

**Comment by MichalMMac** [comment]
Hi there again. I am no longer using my recipe to download Mono framework. I suggest I improve yours and deprecate mine. What do you think?

**Comment by fuzzylogiq** [comment]
This would be greatly appreciated!

**Comment by MichalMMac** [comment]
See #13

**Comment by MichalMMac** [comment]
With #13  merged I am going to deprectate my mono recipes and remove them from my repo in a few months so we can have single set of Mono recipes under autopkg org.

**Comment by MichalMMac** [comment]
I [deprecated](https://github.com/autopkg/MichalMMac-recipes/commit/48594754158cb097eb13af661b4321803b491665) my MonoFramework recipes. Peple should now use orchard Mono recipes instead.

**Comment by MichalMMac** [comment]
I removed the recipes from my repo. Closing.
