### ISSUE TITLE
Blackmagic Desktop Video 

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/orchard-recipes#35]
Hi, Folks 

The Blackmagic Desktop Video download recipe is currently failing with the below error. 

```
DesktopVideo: Processor: com.github.timsutton.download.davinciresolvelite11/BlackMagicURLProvider: Error: Metadata for product is missing at the expected location in feed.
```

I've had a super quick look, and looks like it's failing because the latest release is a windows only release. 

```
Desktop Video 12.5.1
Logo
About Blackmagic Desktop Video Software
Welcome to the Desktop Video software
This software includes everything you need to set up your DeckLink, UltraStudio and Intensity for video capture and playback with your computer.

What's new in Desktop Video 12.5.1
This update fixes a blue screen start up crash seen on some Windows 11 computers.

Windows Specific
Minimum system requirements for Windows
Microsoft Windows 10 or 11 64-bit
Microsoft Windows computer with either Thunderbolt, PCIe slot or USB 3.0 port.
8 GB of system memory.
```

**Comment by stefanj135** [comment]
Hey Paul,
Thanks for the notification and sorry, i'm a little late on to this one (it is the holiday season:) ).  Ill actually be removing all the Black Magic Software out of our repo. We just don't have the requirement for it.  Hopefully that doesn't break things too much for you. 
Cheers,

**Comment by paul-cossey** [comment]
Sorry for the slow reply, @stefanj135!

Thanks for the heads up, I created some recipes for us to use here: https://github.com/autopkg/dataJAR-recipes/tree/master/Blackmagic%20Desktop%20Video 

I'll close this off now as no longer needed.
