### ISSUE TITLE
OxygemXMLEditor issue

### ISSUE THREAD

**Issue by eshirk** [autopkg/orchard-recipes#9]
URLTextSearcher is failing: 
"Error in local.munki.OxygenXMLEditor: Processor: URLTextSearcher: Error: No match found on URL: https://www.oxygenxml.com/xml_editor/download_oxygenxml_editor.html?os=MacOSX"

**Comment by fuzzylogiq** [comment]
Fixed (hopefully) in https://github.com/autopkg/orchard-recipes/commit/a226814b648b7fa1ee4afa82062246f5e2c48c47

**Comment by eshirk** [comment]
Works perfectly for me…thank you for the rapid response!


On Mar 1, 2019, at 5:41 AM, Ben Goodstein <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #9<https://github.com/autopkg/orchard-recipes/issues/9>.
